export const educationEnum = [
  'JSC/JDC/8 PASS',
  'SSC/Secondary',
  'HSC / Higher Secondary',
  'Diploma',
  'Bachelor / Honors',
  'Masters',
  'PHD (Doctor of Philosophy)',
];

export const asianNationalityEnum = [
  'Afghan',
  'Armenian',
  'Azerbaijani',
  'Bahraini',
  'Bangladeshi',
  'Bhutanese',
  'Bruneian',
  'Cambodian',
  'Chinese',
  'Cypriot',
  'Georgian',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Israeli',
  'Japanese',
  'Jordanian',
  'Kazakhstani',
  'Kuwaiti',
  'Kyrgyzstani',
  'Laotian',
  'Lebanese',
  'Malaysian',
  'Maldivian',
  'Mongolian',
  'Burmese',
  'Nepali',
  'North Korean',
  'Omani',
  'Pakistani',
  'Palestinian',
  'Filipino',
  'Qatari',
  'Saudi Arabian',
  'Singaporean',
  'South Korean',
  'Sri Lankan',
  'Syrian',
  'Taiwanese',
  'Tajikistani',
  'Thai',
  'Timorese',
  'Turkish',
  'Turkmenistani',
  'Emirati',
  'Uzbekistani',
  'Vietnamese',
  'Yemeni',
];

export const genderEnum = ['male', 'Female'];
export const socialMediaPlatforms = [
  'Facebook',
  'Github',
  'Instagram',
  'LinkedIn',
  'YouTube',
];

export const profileSearchableFields = [
  'id',
  'gender',
  'contactNo',
  'name.fisrtName',
  'name.lastName',
  'skills',
  'dateOfBirth',
  'nationality',
];

export const profileFilterableFields = [
  'searchTerm',
  'gender',
  'contactNo',
  'name.fisrtName',
  'name.lastName',
  'skills',
  'dateOfBirth',
  'nationality',
];
